image: registry.gitlab.com/fdroid/ci-images-client:latest

before_script:
  - rm -rf fdroidserver
  - mkdir fdroidserver
  - commit=$(git ls-remote https://git.bubu1.eu/Bubu/fdroidserver.git master | cut -f1)
  - echo "Using fdroidserver ${commit}"
  - curl --silent https://git.bubu1.eu/Bubu/fdroidserver/repository/${commit}/archive.tar.gz
      | tar -xz --directory=fdroidserver --strip-components=1
  - export PATH="$PWD/fdroidserver:$PATH"
  - ln -s fdroidserver/gradlew-fdroid fdroidserver/gradle
  - export ANDROID_SDK_ROOT=$ANDROID_HOME
    
lint+test+build:
  script:
    # always report on lint errors to the build log
    - sed -i -e 's,textReport .*,textReport true,' app/build.gradle
    - gradle lint
    - gradle testReleaseUnitTest
    - gradle assembleDebug
  artifacts:
    paths:
    - app/build/reports/

fdroid:build:
  script:
    - cd fdroidrepo
    - PYTHONPATH=. fdroid gencibuild eu.bubu1.fdroidclassic
    - fdroid build --stop -v -l eu.bubu1.fdroidclassic
